"""Data structures for the final requirement review (p9: Requirement Closure)."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


VALID_REVIEW_STATUSES = (
    "COMPLETE",
    "PARTIAL",
    "FAILED",
    "BLOCKED",
    "RISK_ACCEPTED",
)

VALID_EVIDENCE_GRADES = ("A", "B", "C", "D", "E")


@dataclass
class RequirementResult:
    """One verifiable requirement item extracted from the original requirement."""

    requirement_id: str
    description: str = ""
    status: str = "NOT_VERIFIED"       # PASS / PARTIAL / NOT_VERIFIED / FAIL
    evidence_grade: str = ""           # A ~ E
    task_ids: list[str] = field(default_factory=list)
    changed_files: list[str] = field(default_factory=list)
    evidence: list[str] = field(default_factory=list)
    missing_evidence: list[str] = field(default_factory=list)
    tests: list[str] = field(default_factory=list)


@dataclass
class RequirementRisk:
    risk_id: str
    type: str = ""                     # FUNCTIONAL_GAP / INTEGRATION_RISK / ...
    severity: str = "medium"           # high / medium / low
    description: str = ""
    evidence: list[str] = field(default_factory=list)
    recommended_action: str = ""


@dataclass
class FollowupTask:
    """A follow-up task generated by the final re-planner."""

    id: str
    title: str = ""
    project: str = ""
    prompt: str = ""
    depends_on: list[str] = field(default_factory=list)
    allowed_paths: list[str] = field(default_factory=list)
    requirement_ids: list[str] = field(default_factory=list)
    priority: str = "P1"
    reason: str = ""
    acceptance_criteria: list[str] = field(default_factory=list)
    validation_command: str = ""


@dataclass
class RequirementReview:
    """The structured outcome of one final-review round for a run."""

    run_id: str
    status: str                        # one of VALID_REVIEW_STATUSES
    summary: str = ""
    base_revision: str = ""
    final_revision: str = ""
    requirements: list[RequirementResult] = field(default_factory=list)
    risks: list[RequirementRisk] = field(default_factory=list)
    followup_tasks: list[FollowupTask] = field(default_factory=list)
    coverage: dict[str, Any] = field(default_factory=dict)
    risk_level: str = "low"
    raw_response: str = ""

    @property
    def coverage_score(self) -> float:
        """LLM-reported score, or completed/total when the score is missing."""
        try:
            if "score" in self.coverage:
                return float(self.coverage["score"])
        except (TypeError, ValueError):
            pass
        total = self.coverage.get("total") or 0
        completed = self.coverage.get("completed") or 0
        if total > 0:
            return completed / total
        # Fall back to counting requirement statuses.
        n = len(self.requirements)
        if n:
            passed = sum(1 for r in self.requirements if r.status == "PASS")
            return passed / n
        return 0.0

    def to_dict(self) -> dict[str, Any]:
        return {
            "run_id": self.run_id,
            "status": self.status,
            "summary": self.summary,
            "base_revision": self.base_revision,
            "final_revision": self.final_revision,
            "coverage": self.coverage,
            "risk_level": self.risk_level,
            "requirements": [
                {
                    "requirement_id": r.requirement_id,
                    "description": r.description,
                    "status": r.status,
                    "evidence_grade": r.evidence_grade,
                    "task_ids": r.task_ids,
                    "changed_files": r.changed_files,
                    "evidence": r.evidence,
                    "missing_evidence": r.missing_evidence,
                    "tests": r.tests,
                }
                for r in self.requirements
            ],
            "risks": [
                {
                    "risk_id": k.risk_id,
                    "type": k.type,
                    "severity": k.severity,
                    "description": k.description,
                    "evidence": k.evidence,
                    "recommended_action": k.recommended_action,
                }
                for k in self.risks
            ],
            "followup_tasks": [
                {
                    "id": t.id,
                    "title": t.title,
                    "project": t.project,
                    "depends_on": t.depends_on,
                    "allowed_paths": t.allowed_paths,
                    "requirement_ids": t.requirement_ids,
                    "priority": t.priority,
                    "reason": t.reason,
                    "acceptance_criteria": t.acceptance_criteria,
                    "validation_command": t.validation_command,
                }
                for t in self.followup_tasks
            ],
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> RequirementReview:
        review = cls(
            run_id=str(data.get("run_id", "")),
            status=str(data.get("status", "BLOCKED")).upper(),
            summary=str(data.get("summary", "")),
            base_revision=str(data.get("base_revision", "")),
            final_revision=str(data.get("final_revision", "")),
            coverage=dict(data.get("coverage") or {}),
            risk_level=str(data.get("risk_level", "low")).lower(),
        )
        for r in data.get("requirements") or []:
            review.requirements.append(RequirementResult(
                requirement_id=str(r.get("requirement_id", "")),
                description=str(r.get("description", "")),
                status=str(r.get("status", "NOT_VERIFIED")).upper(),
                evidence_grade=str(r.get("evidence_grade", "")).upper(),
                task_ids=[str(x) for x in (r.get("task_ids") or [])],
                changed_files=[str(x) for x in (r.get("changed_files") or [])],
                evidence=[str(x) for x in (r.get("evidence") or [])],
                missing_evidence=[str(x) for x in (r.get("missing_evidence") or [])],
                tests=[str(x) for x in (r.get("tests") or [])],
            ))
        for k in data.get("risks") or []:
            review.risks.append(RequirementRisk(
                risk_id=str(k.get("risk_id", "")),
                type=str(k.get("type", "")),
                severity=str(k.get("severity", "medium")).lower(),
                description=str(k.get("description", "")),
                evidence=[str(x) for x in (k.get("evidence") or [])],
                recommended_action=str(k.get("recommended_action", "")),
            ))
        for t in data.get("followup_tasks") or []:
            review.followup_tasks.append(FollowupTask(
                id=str(t.get("id", "")),
                title=str(t.get("title", "")),
                project=str(t.get("project", "")),
                prompt=str(t.get("prompt", "")),
                depends_on=[str(x) for x in (t.get("depends_on") or [])],
                allowed_paths=[str(x) for x in (t.get("allowed_paths") or [])],
                requirement_ids=[str(x) for x in (t.get("requirement_ids") or [])],
                priority=str(t.get("priority", "P1")),
                reason=str(t.get("reason", "")),
                acceptance_criteria=[str(x) for x in (t.get("acceptance_criteria") or [])],
                validation_command=str(t.get("validation_command", "")),
            ))
        if review.status not in VALID_REVIEW_STATUSES:
            review.status = "BLOCKED"
        return review


# Run lifecycle states (requirement_runs.status)
RUN_PLANNED = "PLANNED"
RUN_EXECUTING = "EXECUTING"
RUN_TASKS_COMPLETED = "TASKS_COMPLETED"
RUN_FINAL_REVIEWING = "FINAL_REVIEWING"
RUN_COMPLETED = "COMPLETED"
RUN_NEEDS_REPLAN = "NEEDS_REPLAN"
RUN_FAILED = "FAILED"
